# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paulus Palace
email: maxpaulus43@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I (Max Paulus) will keep all the things I wish to store in 
  my mind palace. I know that this stuff is supposed to be stored
  in my mind, but I keep it here as just in case.
  The goal of this palace is to keep thoughts and ideas in a well-structured,
  organized storage haven. One which I can also share with other people.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxpaulus43.github.io" # the base hostname & protocol for your site
github_username:  maxpaulus43

# Build settings
markdown: kramdown
